// Каталог товаров — пути к фото в images/catalog/ (при отсутствии файла показывается заглушка)
const DEFAULT_IMAGE = 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="%231a365d"><rect width="120" height="120" rx="8" fill="%23e2e8f0"/><text x="60" y="65" font-family="sans-serif" font-size="12" fill="%234a5568" text-anchor="middle">Фото</text></svg>');

const PRODUCTS = [
  {
    id: 1,
    name: 'Печать для ИП (автоматическая)',
    category: 'ip',
    price: 850,
    description: 'Автоматическая печать для индивидуальных предпринимателей. Оснастка пластиковая, оттиск до 40 мм. Срок изготовления 1–2 дня.',
    image: 'images/catalog/1.jpg',
  },
  {
    id: 2,
    name: 'Печать для ИП (ручная)',
    category: 'ip',
    price: 650,
    description: 'Ручная печать для ИП. Классическая оснастка, надёжный оттиск. Подходит для небольших объёмов.',
    image: 'images/catalog/2.jpg',
  },
  {
    id: 3,
    name: 'Печать для ООО (автоматическая)',
    category: 'ooo',
    price: 1200,
    description: 'Печать организации с автоматической оснасткой. Вмещает полное наименование ООО, ИНН, ОГРН. Диаметр до 45 мм.',
    image: 'images/catalog/3.jpg',
  },
  {
    id: 4,
    name: 'Печать для ООО (ручная)',
    category: 'ooo',
    price: 950,
    description: 'Ручная печать юридического лица. Удобная оснастка, чёткий оттиск на документах.',
    image: 'images/catalog/4.jpg',
  },
  {
    id: 5,
    name: 'Медицинская печать врача',
    category: 'medical',
    price: 750,
    description: 'Печать для медработников. Соответствует требованиям для медицинской документации. Круглая форма.',
    image: 'images/catalog/5.jpg',
  },
  {
    id: 6,
    name: 'Печать медицинской организации',
    category: 'medical',
    price: 1100,
    description: 'Печать для клиник, аптек, лабораторий. С указанием наименования и реквизитов организации.',
    image: 'images/catalog/6.jpg',
  },
  {
    id: 7,
    name: 'Кадастровая печать',
    category: 'cadastral',
    price: 1300,
    description: 'Печать кадастрового инженера. Соответствует требованиям законодательства для кадастровых работ.',
    image: 'images/catalog/7.jpg',
  },
  {
    id: 8,
    name: 'Печать по оттиску',
    category: 'imprint',
    price: 1500,
    description: 'Восстановление печати по имеющемуся оттиску. Точное воспроизведение по образцу. Срок от 2 дней.',
    image: 'images/catalog/8.jpg',
  },
  {
    id: 9,
    name: 'Печать по оттиску (срочно)',
    category: 'imprint',
    price: 2200,
    description: 'Срочное изготовление печати по оттиску. Готовность за 1 рабочий день.',
    image: 'images/catalog/9.jpg',
  },
  {
    id: 10,
    name: 'Оснастка автоматическая',
    category: 'osnastki',
    price: 350,
    description: 'Автоматическая оснастка для печати. Удобная кнопка, ровный оттиск. Подходит для сменных клише.',
    image: 'images/catalog/10.jpg',
  },
  {
    id: 11,
    name: 'Оснастка ручная круглая',
    category: 'osnastki',
    price: 200,
    description: 'Ручная круглая оснастка. Надёжная, под замену клише.',
    image: 'images/catalog/11.jpg',
  },
  {
    id: 12,
    name: 'Оснастка карманная',
    category: 'osnastki',
    price: 280,
    description: 'Компактная карманная оснастка. Удобно носить с собой.',
    image: 'images/catalog/12.jpg',
  },
];
